apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-deployment
  labels:
    app: hackathon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-app
  template:
    metadata:
      labels:
        app: hackathon-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: hackathon
        image: felipecarvalhodesouza/hackathon:latest
        resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: Always
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: mysql-db-core-config
                key: DATABASE_URL
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-db-core-secret
                key: DATABASE_USERNAME
          - name: DATABASE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-db-core-config
                key: DATABASE_PASSWORD
          - name: EMAIL_PASSWORD
            value: "${EMAIL_PASSWORD}"