apiVersion: v1
kind: Service
metadata:
  name: hackathon-service
  labels:
    app: hackathon-app
spec:
  type: LoadBalancer
  selector:
    app: hackathon-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080